steps:
  - name: node:18.15.0
    entrypoint: npm
    args: ['install']
  - name: node:18.15.0
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
