import { Schema } from 'mongoose'

export const beerSchema = new Schema({
  beerName: { type: String, required: true },
  beerType: {
    type: String,
    enum: [
      'WEIZEN',
      'SCHWARZ',
      'HLAGER',
      'EXPORT',
      'DLAGER',
      'KOELSCH',
      'WBOCK',
      'EBOCK',
      'BOCK',
      'BERLINERWEIS',
      'ALT',
      'PILS',
      'ZOIGL',
      'MAERZEN',
      'RAUCH',
      'STOUT',
      'PORTER',
      'PALEALE',
      'ZWICKEL',
      'RADLER',
    ],
  },
  fermentedType: {
    type: String,
    required: true,
    enum: ['TOP', 'BOTTOM', 'BOTH'],
  },
  beerDescription: { type: String, required: false },
  abv: { type: Number, required: true },
  color: {
    type: string,
    enum: [
      'LIGHT',
      'DARK',
      'AMBER',
      'CLOUDY',
      'YELLOW',
      'BROWN',
      'GOLD',
      'BLACK',
      'MAHOGANY',
    ],
    required: true,
  },
  mouthfeel: {
    type: String,
    enum: [
      'LIGHT',
      'FRESH',
      'SWEET',
      'FULL-BODIED',
      'SMOOTH',
      'SOFT',
      'SPARKLING',
      'STRONG',
      'OILY',
      'TANGY',
      'SUBTLE',
    ],
    required: true,
  },
  aroma: {
    type: String,
    enum: [
      'FRUITY',
      'CITRUS',
      'FLOWERY',
      'HOPPY',
      'MALTY',
      'CARAMEL',
      'BERRIES',
      'COFFEE',
      'CHOCOLATE',
      'SMOKE',
      'HERBAL',
      'SOUR',
      'BREAD',
      'ROASTED',
      'BITTERNESS',
    ],
    required: true,
  },
  avgRating: { type: Number, min: 1, max: 10 },
})
